README.md

Add basic project description in README.md

---

.prettierrc
package-lock.json
package.json
src/App.tsx

Remove eslint, install restater

---

snowpack.config.js
src/components/Dock.tsx
src/views/desktop/Desktop.tsx
tsconfig.json

Fix import aliases

---

package-lock.json
package.json
src/components/dock/Dock.tsx
src/stores/dock.store.tsx

Restater works perfectly. Moving to it now

---

package-lock.json
package.json
src/components/dock/Dock.tsx
src/components/dock/dock-item.tsx

The dock is much more realistic now

Fixed up dock animations

---

package-lock.json
package.json
src/components/dock/Dock.tsx
src/stores/dock.store.tsx
src/views/desktop/Desktop.tsx

Restater was a good library, but jotai feels like Svelte, and also doesn't triggers unnecessary re-renders

Jotai in, restater out

---

package-lock.json
package.json
src/components/dock/Dock.tsx
src/components/dock/DockItem.tsx
src/components/menubar/MenuBar.tsx
src/global-provider.tsx
src/hooks/use-theme.ts
src/index.scss
src/stores/dock.store.ts
src/theme.scss
src/theme.ts
src/views/desktop/Desktop.tsx

Actual theme colors need work.

Move to styled-comps, and effective theme switching

---

src/components/menubar/ActionCenter/ActionCenter.tsx

HI PuruVJ,
Yesterday, I discovered your repository thanks to the Kent C.Dodds tweet about it. 
<blockquote class="twitter-tweet"><p lang="en" dir="ltr"><a href="https://t.co/5KFjri4BoS">https://t.co/5KFjri4BoS</a> by <a href="https://twitter.com/puruvjdev?ref_src=twsrc%5Etfw">@puruvjdev</a> built with <a href="https://twitter.com/reactjs?ref_src=twsrc%5Etfw">@reactjs</a> and Vite.js 😍</p>&mdash; Kent C. Dodds (@kentcdodds) <a href="https://twitter.com/kentcdodds/status/1365304499347148801?ref_src=twsrc%5Etfw">February 26, 2021</a></blockquote>
IMHO, I think your project of doing a MacOS interface in ReactJS is amazing. 
So, I really would like to contribute on it (if it doesn't bother you obviously).
I made a little small first PR to add the possibility to update the brightness of the …

Feature: Update brightness of the screen

---

src/components/menubar/ActionCenter/ActionCenter.tsx

Revert "Feature: Update brightness of the screen"

---

index.html

Change title to say Preact not React

---

src/components/Desktop/Window/TrafficLights.tsx
src/components/Desktop/Window/Window.module.scss
src/components/Desktop/Window/Window.tsx
src/components/dock/Dock.tsx
src/components/topbar/TopBar.tsx

Allow window to be maximized
Btw, amazing project!!! I love it!!

Allow window to be maximized

---

src/components/Desktop/Window/TrafficLights.tsx
src/components/Desktop/Window/Window.tsx
src/components/dock/Dock.tsx
src/components/topbar/TopBar.tsx

Revert "Allow window to be maximized"

---

src/components/Desktop/Window/TrafficLights.tsx
src/components/Desktop/Window/Window.tsx
src/components/dock/Dock.tsx
src/components/topbar/TopBar.tsx

Revert "Revert "Allow window to be maximized""

---

src/components/topbar/TopBar.tsx
src/components/topbar/Topbar.module.scss
src/components/topbar/menubar/MenuBar.module.scss
src/components/topbar/menubar/MenuBar.tsx
src/data/menu/finder.menu.config.ts

feat: add apple icon menu in top bar

---

src/components/Desktop/StartupChime.module.scss

Should fix #88 
Yeah Seems to be Working.

hide cursor on boot

---

src/components/topbar/ActionCenter/ActionCenterTile.module.scss

fix: cursor on control panel button area

---

src/components/Desktop/Window/Window.tsx

Double click the window to maximize it

feat: double click window to maximize

---

src/components/Desktop/ContextMenu/ContextMenu.module.scss
src/components/Desktop/ContextMenu/ContextMenu.tsx
src/components/Desktop/Window/Window.module.scss
src/components/Desktop/Window/Window.tsx
src/components/dock/DockItem.module.scss
src/components/dock/DockItem.tsx
src/components/topbar/ActionCenter/ActionCenterShell.module.scss
src/components/topbar/ActionCenter/ActionCenterShell.tsx
src/components/topbar/ActionCenter/ActionCenterSurface.module.scss
src/components/topbar/ActionCenter/ActionCenterSurface.tsx
src/components/topbar/menubar/Menu.module.scss
src/components/topbar/menubar/Menu.tsx
src/views/desktop/Desktop.module.scss
src/views/desktop/Desktop.tsx

remove useTheme wherever its used only for styles

---

src/components/Desktop/StartupChime.tsx

This MR set the property autoplay to audio tag instead of using refs.

Set property autoplay instead of use refs

---

package-lock.json
src/components/apps/Calculator/Calculator.module.scss
src/components/apps/Calculator/Calculator.tsx

[Bug fixes]: 
Apps -> calculator,
1. Fixed key gaps issue 
2. Added animation when clicked on any keys
3. The "AC" button will be changed to "C" when the user will clicked on the number keys

bug fixes for calculator key gaps, click animation and AC/C button
